### ISSUE TITLE
Impossible to create Diagram

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/open_artifacts_for_bedrock#1]
```
yarn run v1.22.22
$ next dev --turbo
  ▲ Next.js 14.2.4 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ⚠ Invalid next.config.mjs options detected:
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ✓ Ready in 1167ms
 ✓ Compiled /api/auth/[...nextauth] in 179ms
[next-auth][warn][NEXTAUTH_URL]
https://next-auth.js.org/warnings#nextauth_url
[next-auth][warn][NO_SECRET]
https://next-auth.js.org/warnings#no_secret
[next-auth][error][JWT_SESSION_ERROR]
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
  message: 'decryption operation failed',
  stack: 'JWEDecryptionFailed: decryption operation failed\n' +
    '    at gcmDecrypt (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:4891:15)\n' +
    '    at decrypt (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:4914:20)\n' +
    '    at flattenedDecrypt (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:6434:52)\n' +
    '    at async compactDecrypt (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:6489:23)\n' +
    '    at async jwtDecrypt (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:7972:23)\n' +
    '    at async Object.decode (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:15801:25)\n' +
    '    at async Object.session (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:17148:34)\n' +
    '    at async AuthHandler (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:19145:37)\n' +
    '    at async NextAuthRouteHandler (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:20693:30)\n' +
    '    at async NextAuth._args$ (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/.next/server/chunks/node_modules_30397c._.js:20728:24)\n' +
    '    at async /Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038\n' +
    '    at async ek.execute (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)\n' +
    '    at async ek.handle (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)\n' +
    '    at async doRender (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1377:42)\n' +
    '    at async cacheEntry.responseCache.get.routeKind (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1587:40)\n' +
    '    at async DevServer.renderToResponseWithComponentsImpl (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1507:28)\n' +
    '    at async DevServer.renderPageComponent (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1931:24)\n' +
    '    at async DevServer.renderToResponseImpl (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1969:32)\n' +
    '    at async DevServer.pipeImpl (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:920:25)\n' +
    '    at async NextNodeServer.handleCatchallRenderRequest (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/next-server.js:272:17)\n' +
    '    at async DevServer.handleRequestImpl (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:816:17)\n' +
    '    at async /Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/dev/next-dev-server.js:339:20\n' +
    '    at async Span.traceAsyncFn (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/trace/trace.js:154:20)\n' +
    '    at async DevServer.handleRequest (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/dev/next-dev-server.js:336:24)\n' +
    '    at async invokeRender (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:174:21)\n' +
    '    at async handleRequest (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:353:24)\n' +
    '    at async requestHandlerImpl (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:377:13)\n' +
    '    at async Server.requestListener (/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/start-server.js:141:13)',
  name: 'JWEDecryptionFailed'
}
 GET /api/auth/session 200 in 406ms
 ○ Compiling /login ...
 ✓ Compiled /login in 1024ms
 GET /api/auth/providers 200 in 78ms
 GET /api/auth/csrf 200 in 31ms
 POST /api/auth/callback/credentials 200 in 26ms
 GET /api/auth/session 200 in 23ms
 POST /api/auth/session 400 in 22ms
 ○ Compiling / ...
 ✓ Compiled / in 541ms
 GET /api/auth/session 200 in 51ms
 ○ Compiling /api/chat ...
 ✓ Compiled /api/chat in 519ms
 ⚠ ./lib/local-sandbox.ts:30:10
lint TP1004 fs.existsSync(???*0*) is very dynamic
  28 |
  29 | function createDirectoryIfNotExists(directoryPath: string): void {
> 30 |     if (!fs.existsSync(directoryPath)) {
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  31 |       try {
  32 |         fs.mkdirSync(directoryPath, { recursive: true });
  33 |         console.log(`Directory created: ${directoryPath}`);

- *0* arguments[0]
  ⚠️  function calls are not analysed yet


The data stream is hanging. Did you forget to close it with `data.close()`?
from diagrams import Cluster, Diagram
from diagrams.aws.network import ELB
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS

with Diagram("Web Server Architecture", show=False):
    lb = ELB("Load Balancer")

    with Cluster("Services"):
        servers = [EC2("App Server1"),
                   EC2("App Server2"),
                   EC2("App Server3")]

    databases = [RDS("Read Replica1"),
                 RDS("Read Replica2"),
                 RDS("Master DB")]

    lb >> servers >> databases
dockerCommand Error: Command failed: docker run --rm -v "/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/workingdir/gmarchan:/app" -w /app python3.10 python viii7m_temp_script.py
Traceback (most recent call last):
  File "/app/viii7m_temp_script.py", line 18, in <module>
    lb >> servers >> databases
TypeError: unsupported operand type(s) for >>: 'list' and 'list'

stdErrStr: "Command failed: docker run --rm -v \"/Users/gmarchan/Documents/PROJECT/open_artifacts_for_bedrock/workingdir/gmarchan:/app\" -w /app python3.10 python viii7m_temp_script.py\nTraceback (most recent call last):\n  File \"/app/viii7m_temp_script.py\", line 18, in <module>\n    lb >> servers >> databases\nTypeError: unsupported operand type(s) for >>: 'list' and 'list'\n"
stdout:
 POST /api/chat 200 in 6624ms
 ```

**Comment by xiehust** [comment]
Did you use claude 3.5 or claude 3? You can past the error back to the input box, and let the claude to fix the error by itself.
If you use claude 3, it might have higher chance of errors
