### ISSUE TITLE
requesting Bedrock error 

### ISSUE THREAD

**Issue by ralaxe** [aws-samples/open_artifacts_for_bedrock#6]
```shell
open_artifacts_for_bedrock]$ yarn dev -- -H 0.0.0.0
yarn run v1.22.22
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ next dev --turbo -H 0.0.0.0
  ▲ Next.js 14.2.5 (turbo)
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000
  - Environments: .env

 ✓ Starting...
 ⚠ Invalid next.config.mjs options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

 ✓ Ready in 1862ms
 ○ Compiling / ...
 ✓ Compiled / in 7.1s
 GET / 200 in 4211ms
 ○ Compiling /api/auth/[...nextauth] ...
 GET /favicon.ico 200 in 1154ms
 ✓ Compiled /api/auth/[...nextauth] in 1320ms
[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
 GET /api/auth/session 200 in 1844ms
 GET /api/auth/session 200 in 61ms
 ○ Compiling /login ...
 ✓ Compiled /login in 592ms
 GET /favicon.ico 200 in 26ms
 GET /api/auth/providers 200 in 56ms
 GET /api/auth/csrf 200 in 23ms
 POST /api/auth/callback/credentials 401 in 31ms
 GET /api/auth/providers 200 in 49ms
 GET /api/auth/csrf 200 in 33ms
 POST /api/auth/callback/credentials 401 in 24ms
 GET /login 200 in 68ms
 GET /favicon.ico 200 in 45ms
 GET /api/auth/session 200 in 73ms
 GET /api/auth/session 200 in 64ms
 GET /api/auth/providers 200 in 47ms
 GET /api/auth/csrf 200 in 23ms
 POST /api/auth/callback/credentials 200 in 30ms
 GET /api/auth/session 200 in 41ms
 POST /api/auth/session 400 in 22ms
 GET /favicon.ico 200 in 65ms
 ○ Compiling /api/chat ...
 ✓ Compiled /api/chat in 2.8s
 ⚠ ./lib/local-sandbox.ts:30:10
lint TP1004 fs.existsSync(???*0*) is very dynamic
  28 |
  29 | function createDirectoryIfNotExists(directoryPath: string): void {
> 30 |     if (!fs.existsSync(directoryPath)) {
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  31 |       try {
  32 |         fs.mkdirSync(directoryPath, { recursive: true });
  33 |         console.log(`Directory created: ${directoryPath}`);

- *0* arguments[0]
  ⚠️  function calls are not analysed yet


using bedrock client specified from env
newMessages: [ { role: 'user', content: [ [Object] ] } ]
 ⨯ TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at request (node:https:366:10)
    at /home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:13855:25
    at new Promise (<anonymous>)
    at NodeHttpHandler.handle (/home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:13805:16)
    at async /home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:15683:34
    at async /home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:14840:28
    at async /home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:11414:54
    at async /home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:18278:34
    at async BedrockChatLanguageModel.doStream (/home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_665899._.js:18676:26)
    at async _retryWithExponentialBackoff (/home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_ai_dist_index_mjs_1ce7e4._.js:93:16)
    at async streamText (/home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/node_modules_ai_dist_index_mjs_1ce7e4._.js:1471:47)
    at async POST (/home/ec2-user/open_artifacts_for_bedrock/.next/server/chunks/_2660ce._.js:299:20)
    at async /home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55038
    at async ek.execute (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45808)
    at async ek.handle (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56292)
    at async doRender (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/ec2-user/open_artifacts_for_bedrock/node_modules/next/dist/server/lib/start-server.js:141:13) {
  code: 'ERR_INVALID_CHAR',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
 POST /api/chat 500 in 3009ms
The data stream is hanging. Did you forget to close it with `data.close()`?
```

**Comment by ralaxe** [comment]
Finally, I discovered the issue: it was the AK/SK credentials. I deleted them and switched to using an IAM role for the EC2 instance.
